const userData = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    age: 14,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 2,
    lastName: "Lannister",
    firstName: "Cersei",
    age: 31,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 3,
    lastName: "Anderson",
    firstName: "Jaime",
    age: 31,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 4,
    lastName: "Stark",
    firstName: "Arya",
    age: 11,
    phoneNumber: "910661623",
    gender: "Female",
    address: "Iskon Park 302-B",
  },
  {
    id: 5,
    lastName: "Targaryen",
    firstName: "Daenerys",
    age: null,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 6,
    lastName: "Melisandre",
    firstName: "Luka",
    age: 150,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 7,
    lastName: "Clifford",
    firstName: "Ferrara",
    age: 44,
    phoneNumber: "910661623",
    gender: "Female",
    address: "Iskon Park 302-B",
  },
  {
    id: 8,
    lastName: "Frances",
    firstName: "Rossini",
    age: 36,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
  {
    id: 9,
    lastName: "Roxie",
    firstName: "Harvey",
    age: 65,
    phoneNumber: "910661623",
    gender: "Male",
    address: "Iskon Park 302-B",
  },
];

module.exports = {userData}
